Modify time first, round after (and strip additional precision).
I've noticed that TestDo_rateLimit_noNetworkCall test fails on Go
master with the following error:

	--- FAIL: TestDo_rateLimit_noNetworkCall (0.00s)
		github_test.go:549: rateLimitErr rate reset = 2017-02-25 01:49:01 +0000 UTC, want 2017-02-25 01:49:01 +0000 UTC m=+60.206993003

(Source: https://travis-ci.org/google/go-github/jobs/205180544.)

This is due to changes in Go 1.9 to perform monotonic elapsed time
measurements. See https://github.com/golang/go/issues/12914 and
https://golang.org/design/12914-monotonic for full details.

Make the test pass by modifying time first, round after, and strip
the monotonic clock reading by using AddDate(0, 0, 0). Doing that
eliminates the unwanted additional monotonic precision from wanted
time, making the expected time equality true.